services:
  - type: web
    name: money-munchkins-2
    runtime: node
    rootDir: products/money-munchkins-2
    buildCommand: npm install --prefix app && npm run build --prefix app
    startCommand: npm run start --prefix app
    healthCheckPath: /api/money-munchkins/health
    autoDeploy: true
