#!/data/data/com.termux/files/usr/bin/bash

# NIA AUTO-BUILDER
# Generates new modules, installs them, and registers them.

BASE_DIR="$HOME/nia-capital-os"
GEN_DIR="$BASE_DIR/core/generated"
REGISTRY="$GEN_DIR/registry.json"

mkdir -p "$GEN_DIR"

# Initialize registry if missing
if [ ! -f "$REGISTRY" ]; then
  echo "[]" > "$REGISTRY"
fi

# Function: create a new module
create_module() {
  local NAME="$1"
  local CODE="$2"
  local FILE="$GEN_DIR/$NAME.js"

  echo "$CODE" > "$FILE"

  # Update registry
  node - <<EOF2
const fs = require("fs");
const reg = JSON.parse(fs.readFileSync("$REGISTRY"));
reg.push({ name: "$NAME", file: "$FILE", timestamp: Date.now() });
fs.writeFileSync("$REGISTRY", JSON.stringify(reg, null, 2));
EOF2

  echo "[NIA AUTO-BUILDER] Module created: $NAME"
}

# Function: auto-generate module code
generate_code() {
  local NAME="$1"

  cat <<EOF3
module.exports = function $NAME() {
  return {
    module: "$NAME",
    status: "active",
    generatedAt: Date.now()
  };
};
EOF3
}

# Function: build a module from name
build_module() {
  local NAME="$1"
  local CODE
  CODE=$(generate_code "$NAME")
  create_module "$NAME" "$CODE"
}

# Function: build multiple modules
build_many() {
  for M in "$@"; do
    build_module "$M"
  done
}

# Function: list generated modules
list_modules() {
  echo "[NIA AUTO-BUILDER] Installed modules:"
  cat "$REGISTRY"
}

# Function: integrate modules into NIA
integrate_modules() {
  local TARGET="$BASE_DIR/core/generated-loader.js"

  cat > "$TARGET" <<EOF4
// AUTO-GENERATED BY NIA AUTO-BUILDER
const fs = require("fs");
const path = require("path");

const registry = JSON.parse(fs.readFileSync("$REGISTRY"));

module.exports = function loadGeneratedModules() {
  const modules = {};
  registry.forEach(entry => {
    const mod = require(entry.file);
    modules[entry.name] = mod;
  });
  return modules;
};
EOF4

  echo "[NIA AUTO-BUILDER] Integration complete."
}

# CLI interface
case "$1" in
  build)
    shift
    build_many "$@"
    ;;
  list)
    list_modules
    ;;
  integrate)
    integrate_modules
    ;;
  *)
    echo "NIA AUTO-BUILDER COMMANDS:"
    echo "  auto-builder.sh build module1 module2 ..."
    echo "  auto-builder.sh list"
    echo "  auto-builder.sh integrate"
    ;;
esac

